import type { Metadata } from "next";
import Nav from "@/components/sections/Nav";
import Hero from "@/components/sections/Hero";
import Header from "@/components/sections/Header";
import Promotion from "@/components/sections/Promotion";
import Services from "@/components/sections/Services";
import Testimonials from "@/components/sections/Testimonials";
import Plans from "@/components/sections/Plans";

export const metadata: Metadata = {
  title: "Enago",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="min-h-screen bg-white pb-16">
      <Header />
      <Nav />
      <Hero />
      <Promotion />
      <Services />
      <Plans />
      <Testimonials />
    </main>
  );
}
